---

- hosts: scylla
#  remote_user: scylla
  gather_facts: yes
  serial: 1
  vars:
    upgrade_version: true
    upgrade_major: false
    skip_installed_scylla_version_check: true
#     scylla_edition: enterprise
#     scylla_version: latest
  roles:
    - ansible-scylla-node

