blank_issues_enabled: false  # Disables blank issue creation
contact_links:
  - name: ðŸš€ Press to open an issue in Jira.
    url: https://scylladb.atlassian.net/browse/ANSROLES
    about: "Opening issues is not allowed in this Github repository."
