---
- hosts: scylla-manager
  vars:
    scylla_clusters:
      - cluster_name: "mydemo"
        host: "{{ groups['scylla'][0]}}"
        auth_token_file: scyllamgr_auth_token.txt
        without_repair: false
    scylla_manager_repo_url: "http://downloads.scylladb.com/rpm/centos/scylladb-manager-2.1.repo"
    #  These will be passed on to the ansible-scylla-node role applied to the Manager node in order to deploy a local Scylla instance
    scylla_manager_db_vars:
      scylla_repos:
        - 'http://repositories.scylladb.com/scylla/repo/****/centos/scylladb-4.1.repo'
      # Only for Ubuntu/Debian
      #scylla_repo_keyserver: 'hkp://keyserver.ubuntu.com:80'
      #scylla_repo_keys:
      #  - 5e08fbd8b5d6ec9c
      #  - 6B2BFD3660EF3F5B
      #  - 17723034C56D4B19
      scylla_dependencies:
        - curl
        - wget

  roles:
    - role: ansible-scylla-manager
